<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SprzetSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('sprzety')->insert([
            [
                'nazwa' => 'Bosch GSH 16-30',
                'opis' => 'Profesjonalny młot udarowy o mocy 1750 W z siłą udaru 41 J. Wyposażony w system Vibration Control, idealny do ciężkich prac rozbiórkowych. Maks. liczba udarów: 1300 min⁻¹. Waga: 17.9 kg.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 237.51,
                'zdjecie_glowne' => 'images/sprzety/młoty-wyburzeniowe-udarowe-1/glowne.webp',
                'folder_zdjec' => 'images/sprzety/młoty-wyburzeniowe-udarowe-1/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Młoty wyburzeniowe / udarowe',
                'upust' => null,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Bosch GSH 16-30',
                'opis' => 'Profesjonalny młot udarowy o mocy 1750 W z siłą udaru 41 J. Wyposażony w system Vibration Control, idealny do ciężkich prac rozbiórkowych. Maks. liczba udarów: 1300 min⁻¹. Waga: 17.9 kg.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 310.48,
                'zdjecie_glowne' => 'images/sprzety/młoty-wyburzeniowe-udarowe-2/glowne.webp',
                'folder_zdjec' => 'images/sprzety/młoty-wyburzeniowe-udarowe-2/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Młoty wyburzeniowe / udarowe',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Makita HM1812',
                'opis' => 'Wyburzeniowy młot Makita z silnikiem 2000 W, energia udaru 72.8 J, system AVT do redukcji drgań. Doskonały do asfaltu i betonu.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 241.22,
                'zdjecie_glowne' => 'images/sprzety/młoty-wyburzeniowe-udarowe-3/glowne.webp',
                'folder_zdjec' => 'images/sprzety/młoty-wyburzeniowe-udarowe-3/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Młoty wyburzeniowe / udarowe',
                'upust' => 10,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Makita HM1812',
                'opis' => 'Wyburzeniowy młot Makita z silnikiem 2000 W, energia udaru 72.8 J, system AVT do redukcji drgań. Doskonały do asfaltu i betonu.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 185.3,
                'zdjecie_glowne' => 'images/sprzety/młoty-wyburzeniowe-udarowe-4/glowne.webp',
                'folder_zdjec' => 'images/sprzety/młoty-wyburzeniowe-udarowe-4/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Młoty wyburzeniowe / udarowe',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Stihl MS 661',
                'opis' => 'Piła spalinowa o mocy 7.3 KM, prowadnica 50 cm, system M-Tronic. Przeznaczona do wymagających prac leśnych.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 136.97,
                'zdjecie_glowne' => 'images/sprzety/pilarki-i-piły-mechaniczne-5/glowne.webp',
                'folder_zdjec' => 'images/sprzety/pilarki-i-piły-mechaniczne-5/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Pilarki i piły mechaniczne',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Stihl MS 661',
                'opis' => 'Piła spalinowa o mocy 7.3 KM, prowadnica 50 cm, system M-Tronic. Przeznaczona do wymagających prac leśnych.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 269.17,
                'zdjecie_glowne' => 'images/sprzety/pilarki-i-piły-mechaniczne-6/glowne.webp',
                'folder_zdjec' => 'images/sprzety/pilarki-i-piły-mechaniczne-6/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Pilarki i piły mechaniczne',
                'upust' => 10,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Husqvarna 550 XP',
                'opis' => 'Piła o mocy 3.0 kW z systemem AutoTune, długość prowadnicy do 50 cm. Idealna dla profesjonalistów.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 150.33,
                'zdjecie_glowne' => 'images/sprzety/pilarki-i-piły-mechaniczne-7/glowne.webp',
                'folder_zdjec' => 'images/sprzety/pilarki-i-piły-mechaniczne-7/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Pilarki i piły mechaniczne',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Husqvarna 550 XP',
                'opis' => 'Piła o mocy 3.0 kW z systemem AutoTune, długość prowadnicy do 50 cm. Idealna dla profesjonalistów.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 291.71,
                'zdjecie_glowne' => 'images/sprzety/pilarki-i-piły-mechaniczne-8/glowne.webp',
                'folder_zdjec' => 'images/sprzety/pilarki-i-piły-mechaniczne-8/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Pilarki i piły mechaniczne',
                'upust' => 10,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Kubota KX019-4',
                'opis' => 'Minikoparka o masie 1.9 tony, silnik 13.8 kW, głębokość kopania 2.58 m, kompaktowe wymiary do pracy w terenie zabudowanym.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 269.87,
                'zdjecie_glowne' => 'images/sprzety/minikoparki-9/glowne.webp',
                'folder_zdjec' => 'images/sprzety/minikoparki-9/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Minikoparki',
                'upust' => 20,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Kubota KX019-4',
                'opis' => 'Minikoparka o masie 1.9 tony, silnik 13.8 kW, głębokość kopania 2.58 m, kompaktowe wymiary do pracy w terenie zabudowanym.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 255.39,
                'zdjecie_glowne' => 'images/sprzety/minikoparki-10/glowne.webp',
                'folder_zdjec' => 'images/sprzety/minikoparki-10/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Minikoparki',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'JCB 8025 ZTS',
                'opis' => 'Minikoparka z zerowym obrotem tyłu, silnik Perkins 20.9 kW, waga 2.7 tony.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 289.02,
                'zdjecie_glowne' => 'images/sprzety/minikoparki-11/glowne.webp',
                'folder_zdjec' => 'images/sprzety/minikoparki-11/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Minikoparki',
                'upust' => 10,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'JCB 8025 ZTS',
                'opis' => 'Minikoparka z zerowym obrotem tyłu, silnik Perkins 20.9 kW, waga 2.7 tony.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 341.78,
                'zdjecie_glowne' => 'images/sprzety/minikoparki-12/glowne.webp',
                'folder_zdjec' => 'images/sprzety/minikoparki-12/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Minikoparki',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Haulotte Compact 10',
                'opis' => 'Podnośnik nożycowy, wysokość robocza 10 m, udźwig 230 kg, napęd elektryczny, kompaktowy design.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 324.37,
                'zdjecie_glowne' => 'images/sprzety/podnośniki-i-zwyżki-13/glowne.webp',
                'folder_zdjec' => 'images/sprzety/podnośniki-i-zwyżki-13/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Podnośniki i zwyżki',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Haulotte Compact 10',
                'opis' => 'Podnośnik nożycowy, wysokość robocza 10 m, udźwig 230 kg, napęd elektryczny, kompaktowy design.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 201.26,
                'zdjecie_glowne' => 'images/sprzety/podnośniki-i-zwyżki-14/glowne.webp',
                'folder_zdjec' => 'images/sprzety/podnośniki-i-zwyżki-14/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Podnośniki i zwyżki',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Genie GS-1932',
                'opis' => 'Zwyżka elektryczna o wysokości roboczej 7.8 m, platforma o udźwigu 227 kg.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 152.08,
                'zdjecie_glowne' => 'images/sprzety/podnośniki-i-zwyżki-15/glowne.webp',
                'folder_zdjec' => 'images/sprzety/podnośniki-i-zwyżki-15/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Podnośniki i zwyżki',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Genie GS-1932',
                'opis' => 'Zwyżka elektryczna o wysokości roboczej 7.8 m, platforma o udźwigu 227 kg.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 343.24,
                'zdjecie_glowne' => 'images/sprzety/podnośniki-i-zwyżki-16/glowne.webp',
                'folder_zdjec' => 'images/sprzety/podnośniki-i-zwyżki-16/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Podnośniki i zwyżki',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Wacker Neuson DPU6555',
                'opis' => 'Płyta rewersyjna o sile 65 kN, silnik diesla Hatz, prędkość robocza do 25 m/min, idealna do gruntu i kostki.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 317.62,
                'zdjecie_glowne' => 'images/sprzety/zagęszczarki-i-ubijaki-17/glowne.webp',
                'folder_zdjec' => 'images/sprzety/zagęszczarki-i-ubijaki-17/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Zagęszczarki i ubijaki',
                'upust' => null,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Wacker Neuson DPU6555',
                'opis' => 'Płyta rewersyjna o sile 65 kN, silnik diesla Hatz, prędkość robocza do 25 m/min, idealna do gruntu i kostki.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 131.25,
                'zdjecie_glowne' => 'images/sprzety/zagęszczarki-i-ubijaki-18/glowne.webp',
                'folder_zdjec' => 'images/sprzety/zagęszczarki-i-ubijaki-18/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Zagęszczarki i ubijaki',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Bomag BPR 60/65',
                'opis' => 'Zagęszczarka rewersyjna o wadze 460 kg, siła odśrodkowa 60 kN, silnik Hatz.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 399.56,
                'zdjecie_glowne' => 'images/sprzety/zagęszczarki-i-ubijaki-19/glowne.webp',
                'folder_zdjec' => 'images/sprzety/zagęszczarki-i-ubijaki-19/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Zagęszczarki i ubijaki',
                'upust' => null,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Bomag BPR 60/65',
                'opis' => 'Zagęszczarka rewersyjna o wadze 460 kg, siła odśrodkowa 60 kN, silnik Hatz.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 325.45,
                'zdjecie_glowne' => 'images/sprzety/zagęszczarki-i-ubijaki-20/glowne.webp',
                'folder_zdjec' => 'images/sprzety/zagęszczarki-i-ubijaki-20/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Zagęszczarki i ubijaki',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Altrad BWE 150',
                'opis' => 'Betoniarka bębnowa o pojemności całkowitej 150 L, napęd 230 V, do prac murarskich i tynkarskich.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 333.13,
                'zdjecie_glowne' => 'images/sprzety/betoniarki-21/glowne.webp',
                'folder_zdjec' => 'images/sprzety/betoniarki-21/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Betoniarki',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Altrad BWE 150',
                'opis' => 'Betoniarka bębnowa o pojemności całkowitej 150 L, napęd 230 V, do prac murarskich i tynkarskich.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 326.31,
                'zdjecie_glowne' => 'images/sprzety/betoniarki-22/glowne.webp',
                'folder_zdjec' => 'images/sprzety/betoniarki-22/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Betoniarki',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Lescha SM145S',
                'opis' => 'Profesjonalna betoniarka bębnowa, pojemność 145 L, silnik 600 W.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 305.65,
                'zdjecie_glowne' => 'images/sprzety/betoniarki-23/glowne.webp',
                'folder_zdjec' => 'images/sprzety/betoniarki-23/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Betoniarki',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Lescha SM145S',
                'opis' => 'Profesjonalna betoniarka bębnowa, pojemność 145 L, silnik 600 W.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 162.73,
                'zdjecie_glowne' => 'images/sprzety/betoniarki-24/glowne.webp',
                'folder_zdjec' => 'images/sprzety/betoniarki-24/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Betoniarki',
                'upust' => 20,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'DeWalt DCD796',
                'opis' => 'Wiertarko-wkrętarka bezszczotkowa 18V, moment obrotowy 70 Nm, 2 biegi, szybkozaciskowy uchwyt 13 mm.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 207.69,
                'zdjecie_glowne' => 'images/sprzety/wiertarki-i-wkrętarki-25/glowne.webp',
                'folder_zdjec' => 'images/sprzety/wiertarki-i-wkrętarki-25/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Wiertarki i wkrętarki',
                'upust' => 20,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'DeWalt DCD796',
                'opis' => 'Wiertarko-wkrętarka bezszczotkowa 18V, moment obrotowy 70 Nm, 2 biegi, szybkozaciskowy uchwyt 13 mm.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 300.02,
                'zdjecie_glowne' => 'images/sprzety/wiertarki-i-wkrętarki-26/glowne.webp',
                'folder_zdjec' => 'images/sprzety/wiertarki-i-wkrętarki-26/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Wiertarki i wkrętarki',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Makita DHP458',
                'opis' => 'Wiertarko-wkrętarka udarowa, 18V, moment 91 Nm, przeznaczona do ciężkich prac.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 256.71,
                'zdjecie_glowne' => 'images/sprzety/wiertarki-i-wkrętarki-27/glowne.webp',
                'folder_zdjec' => 'images/sprzety/wiertarki-i-wkrętarki-27/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Wiertarki i wkrętarki',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Makita DHP458',
                'opis' => 'Wiertarko-wkrętarka udarowa, 18V, moment 91 Nm, przeznaczona do ciężkich prac.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 389.51,
                'zdjecie_glowne' => 'images/sprzety/wiertarki-i-wkrętarki-28/glowne.webp',
                'folder_zdjec' => 'images/sprzety/wiertarki-i-wkrętarki-28/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Wiertarki i wkrętarki',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Cat 906M',
                'opis' => 'Kompaktowa ładowarka kołowa z silnikiem 55 kW, ładowność 1.55 t, idealna do budowy i transportu materiałów.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 239.7,
                'zdjecie_glowne' => 'images/sprzety/ładowarki-29/glowne.webp',
                'folder_zdjec' => 'images/sprzety/ładowarki-29/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Ładowarki',
                'upust' => null,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Cat 906M',
                'opis' => 'Kompaktowa ładowarka kołowa z silnikiem 55 kW, ładowność 1.55 t, idealna do budowy i transportu materiałów.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 190.88,
                'zdjecie_glowne' => 'images/sprzety/ładowarki-30/glowne.webp',
                'folder_zdjec' => 'images/sprzety/ładowarki-30/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Ładowarki',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'JCB 403',
                'opis' => 'Ładowarka kompaktowa o mocy 36.5 kW, udźwig 0.6 t, napęd hydrostatyczny.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 180.42,
                'zdjecie_glowne' => 'images/sprzety/ładowarki-31/glowne.webp',
                'folder_zdjec' => 'images/sprzety/ładowarki-31/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Ładowarki',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'JCB 403',
                'opis' => 'Ładowarka kompaktowa o mocy 36.5 kW, udźwig 0.6 t, napęd hydrostatyczny.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 148.82,
                'zdjecie_glowne' => 'images/sprzety/ładowarki-32/glowne.webp',
                'folder_zdjec' => 'images/sprzety/ładowarki-32/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Ładowarki',
                'upust' => null,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Master DH 752',
                'opis' => 'Osuszacz powietrza o wydajności 46 l/24h, przepływ 350 m³/h, zbiornik 5.7 l.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 201.99,
                'zdjecie_glowne' => 'images/sprzety/osuszacze-i-nagrzewnice-33/glowne.webp',
                'folder_zdjec' => 'images/sprzety/osuszacze-i-nagrzewnice-33/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Osuszacze i nagrzewnice',
                'upust' => null,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Master DH 752',
                'opis' => 'Osuszacz powietrza o wydajności 46 l/24h, przepływ 350 m³/h, zbiornik 5.7 l.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 134.96,
                'zdjecie_glowne' => 'images/sprzety/osuszacze-i-nagrzewnice-34/glowne.webp',
                'folder_zdjec' => 'images/sprzety/osuszacze-i-nagrzewnice-34/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Osuszacze i nagrzewnice',
                'upust' => 20,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Trotec TTK 171 ECO',
                'opis' => 'Profesjonalny osuszacz kondensacyjny 52 l/24h, przepływ powietrza 450 m³/h.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 200.7,
                'zdjecie_glowne' => 'images/sprzety/osuszacze-i-nagrzewnice-35/glowne.webp',
                'folder_zdjec' => 'images/sprzety/osuszacze-i-nagrzewnice-35/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Osuszacze i nagrzewnice',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Trotec TTK 171 ECO',
                'opis' => 'Profesjonalny osuszacz kondensacyjny 52 l/24h, przepływ powietrza 450 m³/h.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 206.01,
                'zdjecie_glowne' => 'images/sprzety/osuszacze-i-nagrzewnice-36/glowne.webp',
                'folder_zdjec' => 'images/sprzety/osuszacze-i-nagrzewnice-36/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Osuszacze i nagrzewnice',
                'upust' => 20,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Fiac AB100/268',
                'opis' => 'Sprężarka tłokowa, zbiornik 100 L, ciśnienie 10 bar, moc silnika 2.2 kW.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 299.86,
                'zdjecie_glowne' => 'images/sprzety/sprężarki-i-kompresory-37/glowne.webp',
                'folder_zdjec' => 'images/sprzety/sprężarki-i-kompresory-37/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Sprężarki i kompresory',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Fiac AB100/268',
                'opis' => 'Sprężarka tłokowa, zbiornik 100 L, ciśnienie 10 bar, moc silnika 2.2 kW.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 186.39,
                'zdjecie_glowne' => 'images/sprzety/sprężarki-i-kompresory-38/glowne.webp',
                'folder_zdjec' => 'images/sprzety/sprężarki-i-kompresory-38/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Sprężarki i kompresory',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Atlas Copco XAS 88',
                'opis' => 'Mobilny kompresor śrubowy, silnik Kubota, 7 bar, 5 m³/min.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 221.57,
                'zdjecie_glowne' => 'images/sprzety/sprężarki-i-kompresory-39/glowne.webp',
                'folder_zdjec' => 'images/sprzety/sprężarki-i-kompresory-39/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Sprężarki i kompresory',
                'upust' => 20,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Atlas Copco XAS 88',
                'opis' => 'Mobilny kompresor śrubowy, silnik Kubota, 7 bar, 5 m³/min.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 260.24,
                'zdjecie_glowne' => 'images/sprzety/sprężarki-i-kompresory-40/glowne.webp',
                'folder_zdjec' => 'images/sprzety/sprężarki-i-kompresory-40/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Sprężarki i kompresory',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Honda EU22i',
                'opis' => 'Agregat inwerterowy, moc 1.8 kW, silnik GX120, bardzo cicha praca, zbiornik 3.6 l.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 164.22,
                'zdjecie_glowne' => 'images/sprzety/agregaty-prądotwórcze-41/glowne.webp',
                'folder_zdjec' => 'images/sprzety/agregaty-prądotwórcze-41/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Agregaty prądotwórcze',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Honda EU22i',
                'opis' => 'Agregat inwerterowy, moc 1.8 kW, silnik GX120, bardzo cicha praca, zbiornik 3.6 l.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 339.65,
                'zdjecie_glowne' => 'images/sprzety/agregaty-prądotwórcze-42/glowne.webp',
                'folder_zdjec' => 'images/sprzety/agregaty-prądotwórcze-42/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Agregaty prądotwórcze',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Fogo FH 6001 R',
                'opis' => 'Agregat 6 kVA, silnik Honda GX390, AVR, rozruch ręczny.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 359.45,
                'zdjecie_glowne' => 'images/sprzety/agregaty-prądotwórcze-43/glowne.webp',
                'folder_zdjec' => 'images/sprzety/agregaty-prądotwórcze-43/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Agregaty prądotwórcze',
                'upust' => 10,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Fogo FH 6001 R',
                'opis' => 'Agregat 6 kVA, silnik Honda GX390, AVR, rozruch ręczny.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 283.02,
                'zdjecie_glowne' => 'images/sprzety/agregaty-prądotwórcze-44/glowne.webp',
                'folder_zdjec' => 'images/sprzety/agregaty-prądotwórcze-44/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Agregaty prądotwórcze',
                'upust' => null,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Krause Corda 3x12',
                'opis' => 'Drabina wielofunkcyjna, 3 segmenty po 12 szczebli, długość max 9 m, certyfikat EN131.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 292.96,
                'zdjecie_glowne' => 'images/sprzety/rusztowania-i-drabiny-45/glowne.webp',
                'folder_zdjec' => 'images/sprzety/rusztowania-i-drabiny-45/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Rusztowania i drabiny',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Krause Corda 3x12',
                'opis' => 'Drabina wielofunkcyjna, 3 segmenty po 12 szczebli, długość max 9 m, certyfikat EN131.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 390.57,
                'zdjecie_glowne' => 'images/sprzety/rusztowania-i-drabiny-46/glowne.webp',
                'folder_zdjec' => 'images/sprzety/rusztowania-i-drabiny-46/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Rusztowania i drabiny',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Altrad Mostostal 5.5m',
                'opis' => 'Rusztowanie aluminiowe jezdne o wysokości roboczej 5.5 m, nośność 200 kg/m².',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 389.5,
                'zdjecie_glowne' => 'images/sprzety/rusztowania-i-drabiny-47/glowne.webp',
                'folder_zdjec' => 'images/sprzety/rusztowania-i-drabiny-47/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Rusztowania i drabiny',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Altrad Mostostal 5.5m',
                'opis' => 'Rusztowanie aluminiowe jezdne o wysokości roboczej 5.5 m, nośność 200 kg/m².',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 229.22,
                'zdjecie_glowne' => 'images/sprzety/rusztowania-i-drabiny-48/glowne.webp',
                'folder_zdjec' => 'images/sprzety/rusztowania-i-drabiny-48/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Rusztowania i drabiny',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Volvo EC220E',
                'opis' => 'Koparka gąsienicowa 22 tony, silnik 129 kW, głębokość kopania 6.7 m, kabina z klimatyzacją.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 179.33,
                'zdjecie_glowne' => 'images/sprzety/koparki-49/glowne.webp',
                'folder_zdjec' => 'images/sprzety/koparki-49/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Koparki',
                'upust' => 10,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Volvo EC220E',
                'opis' => 'Koparka gąsienicowa 22 tony, silnik 129 kW, głębokość kopania 6.7 m, kabina z klimatyzacją.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 242.2,
                'zdjecie_glowne' => 'images/sprzety/koparki-50/glowne.webp',
                'folder_zdjec' => 'images/sprzety/koparki-50/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Koparki',
                'upust' => 10,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Komatsu PC210 LC',
                'opis' => 'Koparka hydrauliczna, masa 22.5 t, silnik 123 kW, zasięg roboczy 9.5 m.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 272.89,
                'zdjecie_glowne' => 'images/sprzety/koparki-51/glowne.webp',
                'folder_zdjec' => 'images/sprzety/koparki-51/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Koparki',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Komatsu PC210 LC',
                'opis' => 'Koparka hydrauliczna, masa 22.5 t, silnik 123 kW, zasięg roboczy 9.5 m.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 163.56,
                'zdjecie_glowne' => 'images/sprzety/koparki-52/glowne.webp',
                'folder_zdjec' => 'images/sprzety/koparki-52/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Koparki',
                'upust' => null,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Honda WT30X',
                'opis' => 'Pompa spalinowa do wody brudnej, przepływ 1100 l/min, silnik GX270, waga 61 kg.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 225.69,
                'zdjecie_glowne' => 'images/sprzety/pompy-wodne-53/glowne.webp',
                'folder_zdjec' => 'images/sprzety/pompy-wodne-53/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Pompy wodne',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Honda WT30X',
                'opis' => 'Pompa spalinowa do wody brudnej, przepływ 1100 l/min, silnik GX270, waga 61 kg.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 320.54,
                'zdjecie_glowne' => 'images/sprzety/pompy-wodne-54/glowne.webp',
                'folder_zdjec' => 'images/sprzety/pompy-wodne-54/',
                'stan_techniczny' => 'naprawa',
                'kategoria' => 'Pompy wodne',
                'upust' => null,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Koshin SEH-80X',
                'opis' => 'Pompa do czystej wody, wydajność 1050 l/min, silnik Honda GX160.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 252.22,
                'zdjecie_glowne' => 'images/sprzety/pompy-wodne-55/glowne.webp',
                'folder_zdjec' => 'images/sprzety/pompy-wodne-55/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Pompy wodne',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Koshin SEH-80X',
                'opis' => 'Pompa do czystej wody, wydajność 1050 l/min, silnik Honda GX160.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 369.47,
                'zdjecie_glowne' => 'images/sprzety/pompy-wodne-56/glowne.webp',
                'folder_zdjec' => 'images/sprzety/pompy-wodne-56/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Pompy wodne',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Bosch GWS 22-230',
                'opis' => 'Szlifierka kątowa 230 mm, moc 2200 W, system Soft Start, obroty 6500/min.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 190.76,
                'zdjecie_glowne' => 'images/sprzety/szlifierki-i-przecinarki-57/glowne.webp',
                'folder_zdjec' => 'images/sprzety/szlifierki-i-przecinarki-57/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Szlifierki i przecinarki',
                'upust' => 20,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Bosch GWS 22-230',
                'opis' => 'Szlifierka kątowa 230 mm, moc 2200 W, system Soft Start, obroty 6500/min.',
                'dostepnosc' => 'rezerwacja',
                'cena_wynajmu' => 256.58,
                'zdjecie_glowne' => 'images/sprzety/szlifierki-i-przecinarki-58/glowne.webp',
                'folder_zdjec' => 'images/sprzety/szlifierki-i-przecinarki-58/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Szlifierki i przecinarki',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Makita DGA900',
                'opis' => 'Szlifierka akumulatorowa 230 mm, 18V x2, technologia ADT, BLDC silnik.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 202.78,
                'zdjecie_glowne' => 'images/sprzety/szlifierki-i-przecinarki-59/glowne.webp',
                'folder_zdjec' => 'images/sprzety/szlifierki-i-przecinarki-59/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Szlifierki i przecinarki',
                'upust' => 5,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Makita DGA900',
                'opis' => 'Szlifierka akumulatorowa 230 mm, 18V x2, technologia ADT, BLDC silnik.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 332.38,
                'zdjecie_glowne' => 'images/sprzety/szlifierki-i-przecinarki-60/glowne.webp',
                'folder_zdjec' => 'images/sprzety/szlifierki-i-przecinarki-60/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Szlifierki i przecinarki',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Spectra Precision LL300N',
                'opis' => 'Laser rotacyjny z kompensacją elektroniczną, dokładność ±2.2 mm/30 m, zasięg do 500 m.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 205.54,
                'zdjecie_glowne' => 'images/sprzety/lasery-budowlane-i-niwelatory-61/glowne.webp',
                'folder_zdjec' => 'images/sprzety/lasery-budowlane-i-niwelatory-61/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Lasery budowlane i niwelatory',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Spectra Precision LL300N',
                'opis' => 'Laser rotacyjny z kompensacją elektroniczną, dokładność ±2.2 mm/30 m, zasięg do 500 m.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 224.56,
                'zdjecie_glowne' => 'images/sprzety/lasery-budowlane-i-niwelatory-62/glowne.webp',
                'folder_zdjec' => 'images/sprzety/lasery-budowlane-i-niwelatory-62/',
                'stan_techniczny' => 'nowy',
                'kategoria' => 'Lasery budowlane i niwelatory',
                'upust' => 15,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Topcon RL-H5A',
                'opis' => 'Laser budowlany o zasięgu do 800 m, dokładność ±10 arc sec, IP66, tryb samopoziomujący.',
                'dostepnosc' => 'niedostepny',
                'cena_wynajmu' => 351.86,
                'zdjecie_glowne' => 'images/sprzety/lasery-budowlane-i-niwelatory-63/glowne.webp',
                'folder_zdjec' => 'images/sprzety/lasery-budowlane-i-niwelatory-63/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Lasery budowlane i niwelatory',
                'upust' => 10,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
            [
                'nazwa' => 'Topcon RL-H5A',
                'opis' => 'Laser budowlany o zasięgu do 800 m, dokładność ±10 arc sec, IP66, tryb samopoziomujący.',
                'dostepnosc' => 'dostepny',
                'cena_wynajmu' => 197.66,
                'zdjecie_glowne' => 'images/sprzety/lasery-budowlane-i-niwelatory-64/glowne.webp',
                'folder_zdjec' => 'images/sprzety/lasery-budowlane-i-niwelatory-64/',
                'stan_techniczny' => 'uzywany',
                'kategoria' => 'Lasery budowlane i niwelatory',
                'upust' => 20,
                'ilosc_wypozyczen' => rand(10, 200),
            ],
        ]);
    }
}
