<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'first_name' => 'Jan',
                'last_name' => 'Kowalski',
                'phone' => '600123456',
                'email' => 'jan.kowalski@example.com',
                'password' => Hash::make('password123'),
                'address' => 'ul. Przykładowa 1, 00-001 Warszawa',
                'shipping_address' => 'ul. Magazynowa 10, 00-002 Warszawa',
                'payment_token' => null,
                'payment_provider' => null,
                'role' => 'klient',
                'rentals_count' => 2,
                'account_balance' => 8500.00,
                'email_verified_at' => now(),
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Anna',
                'last_name' => 'Nowak',
                'phone' => '501765432',
                'email' => 'admin@example.com',
                'password' => Hash::make('adminadmin'),
                'address' => 'ul. Admina 5, 00-003 Kraków',
                'shipping_address' => null,
                'payment_token' => null,
                'payment_provider' => null,
                'role' => 'administrator',
                'rentals_count' => 0,
                'account_balance' => 30.00,
                'email_verified_at' => now(),
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Dodatkowi klienci
            [
                'first_name' => 'Tomasz',
                'last_name' => 'Wiśniewski',
                'phone' => '500222333',
                'email' => 'tomasz.wisniewski@example.com',
                'password' => Hash::make('haslo123'),
                'address' => 'ul. Zielona 20, 01-100 Poznań',
                'shipping_address' => 'ul. Zielona 20, 01-100 Poznań',
                'payment_token' => null,
                'payment_provider' => null,
                'role' => 'klient',
                'rentals_count' => 1,
                'account_balance' => 75.00,
                'email_verified_at' => now(),
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Katarzyna',
                'last_name' => 'Dąbrowska',
                'phone' => '790333444',
                'email' => 'katarzyna.dabrowska@example.com',
                'password' => Hash::make('sekretnehaslo'),
                'address' => 'ul. Leśna 12, 02-345 Gdańsk',
                'shipping_address' => 'ul. Leśna 12, 02-345 Gdańsk',
                'payment_token' => null,
                'payment_provider' => null,
                'role' => 'klient',
                'rentals_count' => 3,
                'account_balance' => 200.00,
                'email_verified_at' => now(),
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Paweł',
                'last_name' => 'Maj',
                'phone' => '601444555',
                'email' => 'pawel.maj@example.com',
                'password' => Hash::make('majowehaslo'),
                'address' => 'ul. Spacerowa 7, 03-567 Lublin',
                'shipping_address' => 'ul. Spacerowa 7, 03-567 Lublin',
                'payment_token' => null,
                'payment_provider' => null,
                'role' => 'klient',
                'rentals_count' => 0,
                'account_balance' => 0.00,
                'email_verified_at' => now(),
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Magdalena',
                'last_name' => 'Kaczmarek',
                'phone' => '789111222',
                'email' => 'magdalena.kaczmarek@example.com',
                'password' => Hash::make('bezpieczne123'),
                'address' => 'ul. Główna 33, 04-321 Rzeszów',
                'shipping_address' => 'ul. Główna 33, 04-321 Rzeszów',
                'payment_token' => null,
                'payment_provider' => null,
                'role' => 'klient',
                'rentals_count' => 5,
                'account_balance' => 320.00,
                'email_verified_at' => now(),
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
